### ISSUE TITLE
Redundanter Code

### ISSUE THREAD

**Issue by XVirtDevl** [Kinetize/RlyLittleEngine#1]
Nach den include guards einer Header Datei ist es nicht noch notwendig #pragma once zu schreiben, es verkompliziert den Code und ist nicht Compiler unabhängig.
MfG Alex.

**Comment by Kinetize** [comment]
An für sich ja, so habe ich das auch immer gehandhabt, aber in ner Forumsdiskussiom wurde von nem studierten Informatiker erzählt es würde in manchen Fällen durchaus Sinn machen und schadet nicht...
Vlt hau ich das trotzdem ma raus mal schauen

**Comment by XVirtDevl** [comment]
Geht klar wollte eigentlich nur mal das issue system testen :D

**Comment by Kinetize** [comment]
Läuft gut :D
